#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: POST

authentication:
    path: /authentication_token
    controller: App\Controller\AuthController::getTokenUser
